-- SEED PRODUCTS
INSERT INTO products (name, unit) VALUES
('Tomate', 'unidad'),
('Lechuga', 'unidad'),
('Pechuga de Pollo', 'g'),
('Manzana', 'unidad'),
('Plátano', 'unidad'),
('Detergente', 'bote'),
('Jabón', 'bote'),
('Papel Higiénico', 'rollo'),
('Zanahoria', 'unidad'),
('Carne de ternera', 'g'),
('Cebolla', 'unidad'),
('Ajo', 'unidad'),
('Arroz', 'kg'),
('Leche', 'litro'),
('Huevos', 'unidad'),
('Pan', 'unidad'),
('Queso rallado', 'bolsa'),
('Yogur', 'unidad'),
('Aceite de Oliva', 'litro'),
('Sal', 'kg'),
('Azúcar', 'kg'),
('Café', 'unidad'),
('Té', 'caja'),
('Pasta', 'g'),
('Mantequilla', 'unidad'),
('Cereal', 'caja'),
('Zumo de Naranja', 'litro'),
('Atún', 'lata'),
('Galletas', 'paquete'),
('Helado', 'litro'),
('Salsa de Tomate', 'botella'),
('Mayonesa', 'botella'),
('Mostaza', 'botella'),
('Ketchup', 'botella'),
('Vinagre', 'litro'),
('Harina', 'kg'),
('Levadura', 'unidad');

-- SEED STORES
INSERT INTO store (name) VALUES
('N/A'),
('Lidl'),
('Carrefour'),
('Aldi'),
('Mercadona');

-- SEED SHOPPING LIST
INSERT INTO shopping_list (product_id, amount, store_id) VALUES
((SELECT id FROM products WHERE name = 'Tomate' LIMIT 1), 5, (SELECT id FROM store WHERE name = 'Lidl' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Lechuga' LIMIT 1), 3, (SELECT id FROM store WHERE name = 'Lidl' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Pechuga de Pollo' LIMIT 1), 700, (SELECT id FROM store WHERE name = 'Lidl' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Manzana' LIMIT 1), 4, (SELECT id FROM store WHERE name = 'Lidl' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Plátano' LIMIT 1), 6, (SELECT id FROM store WHERE name = 'Lidl' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Detergente' LIMIT 1), 2, (SELECT id FROM store WHERE name = 'Lidl' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Jabón' LIMIT 1), 8, (SELECT id FROM store WHERE name = 'Lidl' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Papel Higiénico' LIMIT 1), 10, (SELECT id FROM store WHERE name = 'Lidl' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Zanahoria' LIMIT 1), 1, (SELECT id FROM store WHERE name = 'Lidl' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Carne de ternera' LIMIT 1), 900, (SELECT id FROM store WHERE name = 'Lidl' LIMIT 1));

-- SEED PANTRY
INSERT INTO pantry (product_id, amount) VALUES
((SELECT id FROM products WHERE name = 'Cebolla' LIMIT 1), 4),
((SELECT id FROM products WHERE name = 'Ajo' LIMIT 1), 2),
((SELECT id FROM products WHERE name = 'Arroz' LIMIT 1), 5),
((SELECT id FROM products WHERE name = 'Leche' LIMIT 1), 6),
((SELECT id FROM products WHERE name = 'Huevos' LIMIT 1), 18),
((SELECT id FROM products WHERE name = 'Pan' LIMIT 1), 1),
((SELECT id FROM products WHERE name = 'Queso rallado' LIMIT 1), 2),
((SELECT id FROM products WHERE name = 'Yogur' LIMIT 1), 6),
((SELECT id FROM products WHERE name = 'Aceite de Oliva' LIMIT 1), 10),
((SELECT id FROM products WHERE name = 'Sal' LIMIT 1), 2);

-- SEED TAGS
INSERT INTO tag (name, type) VALUES
('Limpieza', 'Product'),
('Verdura', 'Product'),
('Fruta', 'Product'),
('Carne', 'Product'),
('Lácteo', 'Product'),
('Cereal', 'Product'),
('Bebida', 'Product'),
('Condimento', 'Product'),
('Panadería', 'Product'),
('Snacks', 'Product');

-- ASSIGN TAGS TO PRODUCTS
INSERT INTO product_tag (product_id, tag_id) VALUES
((SELECT id FROM products WHERE name = 'Tomate' LIMIT 1), (SELECT id FROM tag WHERE name = 'Verdura' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Lechuga' LIMIT 1), (SELECT id FROM tag WHERE name = 'Verdura' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Pechuga de Pollo' LIMIT 1), (SELECT id FROM tag WHERE name = 'Carne' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Manzana' LIMIT 1), (SELECT id FROM tag WHERE name = 'Fruta' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Plátano' LIMIT 1), (SELECT id FROM tag WHERE name = 'Fruta' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Detergente' LIMIT 1), (SELECT id FROM tag WHERE name = 'Limpieza' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Jabón' LIMIT 1), (SELECT id FROM tag WHERE name = 'Limpieza' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Papel Higiénico' LIMIT 1), (SELECT id FROM tag WHERE name = 'Limpieza' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Zanahoria' LIMIT 1), (SELECT id FROM tag WHERE name = 'Verdura' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Carne de ternera' LIMIT 1), (SELECT id FROM tag WHERE name = 'Carne' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Cebolla' LIMIT 1), (SELECT id FROM tag WHERE name = 'Verdura' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Ajo' LIMIT 1), (SELECT id FROM tag WHERE name = 'Verdura' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Arroz' LIMIT 1), (SELECT id FROM tag WHERE name = 'Cereal' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Leche' LIMIT 1), (SELECT id FROM tag WHERE name = 'Lácteo' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Huevos' LIMIT 1), (SELECT id FROM tag WHERE name = 'Lácteo' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Pan' LIMIT 1), (SELECT id FROM tag WHERE name = 'Panadería' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Queso rallado' LIMIT 1), (SELECT id FROM tag WHERE name = 'Lácteo' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Yogur' LIMIT 1), (SELECT id FROM tag WHERE name = 'Lácteo' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Aceite de Oliva' LIMIT 1), (SELECT id FROM tag WHERE name = 'Condimento' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Sal' LIMIT 1), (SELECT id FROM tag WHERE name = 'Condimento' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Azúcar' LIMIT 1), (SELECT id FROM tag WHERE name = 'Condimento' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Café' LIMIT 1), (SELECT id FROM tag WHERE name = 'Bebida' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Té' LIMIT 1), (SELECT id FROM tag WHERE name = 'Bebida' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Pasta' LIMIT 1), (SELECT id FROM tag WHERE name = 'Cereal' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Mantequilla' LIMIT 1), (SELECT id FROM tag WHERE name = 'Lácteo' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Cereal' LIMIT 1), (SELECT id FROM tag WHERE name = 'Cereal' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Zumo de Naranja' LIMIT 1), (SELECT id FROM tag WHERE name = 'Bebida' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Atún' LIMIT 1), (SELECT id FROM tag WHERE name = 'Snacks' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Galletas' LIMIT 1), (SELECT id FROM tag WHERE name = 'Snacks' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Helado' LIMIT 1), (SELECT id FROM tag WHERE name = 'Snacks' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Salsa de Tomate' LIMIT 1), (SELECT id FROM tag WHERE name = 'Condimento' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Mayonesa' LIMIT 1), (SELECT id FROM tag WHERE name = 'Condimento' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Mostaza' LIMIT 1), (SELECT id FROM tag WHERE name = 'Condimento' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Ketchup' LIMIT 1), (SELECT id FROM tag WHERE name = 'Condimento' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Vinagre' LIMIT 1), (SELECT id FROM tag WHERE name = 'Condimento' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Harina' LIMIT 1), (SELECT id FROM tag WHERE name = 'Cereal' LIMIT 1)),
((SELECT id FROM products WHERE name = 'Levadura' LIMIT 1), (SELECT id FROM tag WHERE name = 'Cereal' LIMIT 1));
